backend:
  name: github
  repo: kronkm/personal-website

media_folder: 'content/uploads'
public_folder: ../uploads

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/posts'
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
